// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Num.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Num_h__
#define __Num_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Message
{

class Monitor;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Message::Monitor>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Message::Monitor*);

}

}

namespace Message
{

class Monitor;
bool operator==(const Monitor&, const Monitor&);
bool operator<(const Monitor&, const Monitor&);
::Ice::Object* upCast(::Message::Monitor*);
typedef ::IceInternal::Handle< ::Message::Monitor> MonitorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Message::Monitor> MonitorPrx;
void __patch(MonitorPtr&, const ::Ice::ObjectPtr&);

}

namespace Message
{

struct Num
{
    ::Ice::Long value;

    bool operator==(const Num& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(value != __rhs.value)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Num& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(value < __rhs.value)
        {
            return true;
        }
        else if(__rhs.value < value)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Num& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const Num& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const Num& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const Num& __rhs) const
    {
        return !operator<(__rhs);
    }
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::Message::Num>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 8;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::Message::Num, S>
{
    static void write(S* __os, const ::Message::Num& v)
    {
        __os->write(v.value);
    }
};

template<class S>
struct StreamReader< ::Message::Num, S>
{
    static void read(S* __is, ::Message::Num& v)
    {
        __is->read(v.value);
    }
};

}

namespace Message
{

class Callback_Monitor_publish_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Monitor_publish_Base> Callback_Monitor_publishPtr;

}

namespace IceProxy
{

namespace Message
{

class Monitor : virtual public ::IceProxy::Ice::Object
{
public:

    void publish(const ::Message::Num& m)
    {
        publish(m, 0);
    }
    void publish(const ::Message::Num& m, const ::Ice::Context& __ctx)
    {
        publish(m, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_publish(const ::Message::Num& m, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_publish(m, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_publish(const ::Message::Num& m, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_publish(m, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_publish(const ::Message::Num& m, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_publish(m, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_publish(const ::Message::Num& m, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_publish(m, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m)
    {
        return begin_publish(m, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m, const ::Ice::Context& __ctx)
    {
        return begin_publish(m, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_publish(m, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_publish(m, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m, const ::Message::Callback_Monitor_publishPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_publish(m, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num& m, const ::Ice::Context& __ctx, const ::Message::Callback_Monitor_publishPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_publish(m, &__ctx, __del, __cookie);
    }

    void end_publish(const ::Ice::AsyncResultPtr&);
    
private:

    void publish(const ::Message::Num&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_publish(const ::Message::Num&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Monitor> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_secure(bool __secure) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_twoway() const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_oneway() const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_batchOneway() const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_datagram() const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_batchDatagram() const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_compress(bool __compress) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Monitor> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Monitor*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Message
{

class Monitor : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void publish(const ::Message::Num&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Message
{

class Monitor : virtual public ::IceDelegate::Message::Monitor,
                virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void publish(const ::Message::Num&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Message
{

class Monitor : virtual public ::IceDelegate::Message::Monitor,
                virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void publish(const ::Message::Num&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Message
{

class Monitor : virtual public ::Ice::Object
{
public:

    typedef MonitorPrx ProxyType;
    typedef MonitorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void publish(const ::Message::Num&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___publish(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Monitor& l, const Monitor& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Monitor& l, const Monitor& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Message
{

template<class T>
class CallbackNC_Monitor_publish : public Callback_Monitor_publish_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Monitor_publish(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Monitor_publishPtr
newCallback_Monitor_publish(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Monitor_publish<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Monitor_publishPtr
newCallback_Monitor_publish(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Monitor_publish<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Monitor_publishPtr
newCallback_Monitor_publish(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Monitor_publish<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Monitor_publishPtr
newCallback_Monitor_publish(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Monitor_publish<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Monitor_publish : public Callback_Monitor_publish_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Monitor_publish(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Monitor_publishPtr
newCallback_Monitor_publish(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Monitor_publish<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Monitor_publishPtr
newCallback_Monitor_publish(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Monitor_publish<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Monitor_publishPtr
newCallback_Monitor_publish(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Monitor_publish<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Monitor_publishPtr
newCallback_Monitor_publish(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Monitor_publish<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
