// Generated by gencpp from file RosIceMessage/MotorsSrv.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_MOTORSSRV_H
#define ROSICEMESSAGE_MESSAGE_MOTORSSRV_H

#include <ros/service_traits.h>


#include <RosIceMessage/MotorsSrvRequest.h>
#include <RosIceMessage/MotorsSrvResponse.h>


namespace RosIceMessage
{

struct MotorsSrv
{

typedef MotorsSrvRequest Request;
typedef MotorsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorsSrv
} // namespace RosIceMessage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RosIceMessage::MotorsSrv > {
  static const char* value()
  {
    return "24bb124caf523ca2ec83a12be4206043";
  }

  static const char* value(const ::RosIceMessage::MotorsSrv&) { return value(); }
};

template<>
struct DataType< ::RosIceMessage::MotorsSrv > {
  static const char* value()
  {
    return "RosIceMessage/MotorsSrv";
  }

  static const char* value(const ::RosIceMessage::MotorsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::RosIceMessage::MotorsSrvRequest> should match 
// service_traits::MD5Sum< ::RosIceMessage::MotorsSrv > 
template<>
struct MD5Sum< ::RosIceMessage::MotorsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RosIceMessage::MotorsSrv >::value();
  }
  static const char* value(const ::RosIceMessage::MotorsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RosIceMessage::MotorsSrvRequest> should match 
// service_traits::DataType< ::RosIceMessage::MotorsSrv > 
template<>
struct DataType< ::RosIceMessage::MotorsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::RosIceMessage::MotorsSrv >::value();
  }
  static const char* value(const ::RosIceMessage::MotorsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RosIceMessage::MotorsSrvResponse> should match 
// service_traits::MD5Sum< ::RosIceMessage::MotorsSrv > 
template<>
struct MD5Sum< ::RosIceMessage::MotorsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RosIceMessage::MotorsSrv >::value();
  }
  static const char* value(const ::RosIceMessage::MotorsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RosIceMessage::MotorsSrvResponse> should match 
// service_traits::DataType< ::RosIceMessage::MotorsSrv > 
template<>
struct DataType< ::RosIceMessage::MotorsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::RosIceMessage::MotorsSrv >::value();
  }
  static const char* value(const ::RosIceMessage::MotorsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_MOTORSSRV_H
