// Generated by gencpp from file RosIceMessage/MotorData.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_MOTORDATA_H
#define ROSICEMESSAGE_MESSAGE_MOTORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RosIceMessage
{
template <class ContainerAllocator>
struct MotorData_
{
  typedef MotorData_<ContainerAllocator> Type;

  MotorData_()
    : motorW(0.0)
    , motorV(0.0)
    , motorL(0.0)  {
    }
  MotorData_(const ContainerAllocator& _alloc)
    : motorW(0.0)
    , motorV(0.0)
    , motorL(0.0)  {
    }



   typedef float _motorW_type;
  _motorW_type motorW;

   typedef float _motorV_type;
  _motorV_type motorV;

   typedef float _motorL_type;
  _motorL_type motorL;




  typedef boost::shared_ptr< ::RosIceMessage::MotorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosIceMessage::MotorData_<ContainerAllocator> const> ConstPtr;

}; // struct MotorData_

typedef ::RosIceMessage::MotorData_<std::allocator<void> > MotorData;

typedef boost::shared_ptr< ::RosIceMessage::MotorData > MotorDataPtr;
typedef boost::shared_ptr< ::RosIceMessage::MotorData const> MotorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosIceMessage::MotorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosIceMessage::MotorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RosIceMessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'RosIceMessage': ['/home/ace15/Documents/JdeRobot/GoogleSummer/JdeRobot2015/catkin_ws/src/RosIceMessage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosIceMessage::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a078088a1e96aec90064d1cf6dbf2336";
  }

  static const char* value(const ::RosIceMessage::MotorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa078088a1e96aec9ULL;
  static const uint64_t static_value2 = 0x0064d1cf6dbf2336ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosIceMessage::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/MotorData";
  }

  static const char* value(const ::RosIceMessage::MotorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosIceMessage::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motorW\n\
float32 motorV\n\
float32 motorL\n\
";
  }

  static const char* value(const ::RosIceMessage::MotorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosIceMessage::MotorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorW);
      stream.next(m.motorV);
      stream.next(m.motorL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosIceMessage::MotorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosIceMessage::MotorData_<ContainerAllocator>& v)
  {
    s << indent << "motorW: ";
    Printer<float>::stream(s, indent + "  ", v.motorW);
    s << indent << "motorV: ";
    Printer<float>::stream(s, indent + "  ", v.motorV);
    s << indent << "motorL: ";
    Printer<float>::stream(s, indent + "  ", v.motorL);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_MOTORDATA_H
