// Generated by gencpp from file RosIceMessage/MotorsSrvRequest.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_MOTORSSRVREQUEST_H
#define ROSICEMESSAGE_MESSAGE_MOTORSSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RosIceMessage
{
template <class ContainerAllocator>
struct MotorsSrvRequest_
{
  typedef MotorsSrvRequest_<ContainerAllocator> Type;

  MotorsSrvRequest_()
    : alpha(false)  {
    }
  MotorsSrvRequest_(const ContainerAllocator& _alloc)
    : alpha(false)  {
    }



   typedef uint8_t _alpha_type;
  _alpha_type alpha;




  typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsSrvRequest_

typedef ::RosIceMessage::MotorsSrvRequest_<std::allocator<void> > MotorsSrvRequest;

typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvRequest > MotorsSrvRequestPtr;
typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvRequest const> MotorsSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RosIceMessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'RosIceMessage': ['/home/ace15/Documents/JdeRobot/GoogleSummer/JdeRobot2015/catkin_ws/src/RosIceMessage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "368a37d96756034682f7eca42ae8374b";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x368a37d967560346ULL;
  static const uint64_t static_value2 = 0x82f7eca42ae8374bULL;
};

template<class ContainerAllocator>
struct DataType< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/MotorsSrvRequest";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool alpha\n\
";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.alpha);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorsSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosIceMessage::MotorsSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "alpha: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.alpha);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_MOTORSSRVREQUEST_H
