// Generated by gencpp from file RosIceMessage/MotorsSrvResponse.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_MOTORSSRVRESPONSE_H
#define ROSICEMESSAGE_MESSAGE_MOTORSSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RosIceMessage/MotorData.h>

namespace RosIceMessage
{
template <class ContainerAllocator>
struct MotorsSrvResponse_
{
  typedef MotorsSrvResponse_<ContainerAllocator> Type;

  MotorsSrvResponse_()
    : motorMsg()  {
    }
  MotorsSrvResponse_(const ContainerAllocator& _alloc)
    : motorMsg(_alloc)  {
    }



   typedef  ::RosIceMessage::MotorData_<ContainerAllocator>  _motorMsg_type;
  _motorMsg_type motorMsg;




  typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorsSrvResponse_

typedef ::RosIceMessage::MotorsSrvResponse_<std::allocator<void> > MotorsSrvResponse;

typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvResponse > MotorsSrvResponsePtr;
typedef boost::shared_ptr< ::RosIceMessage::MotorsSrvResponse const> MotorsSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RosIceMessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'RosIceMessage': ['/home/ace15/Documents/JdeRobot/GoogleSummer/JdeRobot2015/catkin_ws/src/RosIceMessage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6849935887438106a7d07d7857217f3";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc684993588743810ULL;
  static const uint64_t static_value2 = 0x6a7d07d7857217f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/MotorsSrvResponse";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/MotorData motorMsg\n\
\n\
\n\
================================================================================\n\
MSG: RosIceMessage/MotorData\n\
float32 motorW\n\
float32 motorV\n\
float32 motorL\n\
";
  }

  static const char* value(const ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorMsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorsSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosIceMessage::MotorsSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "motorMsg: ";
    s << std::endl;
    Printer< ::RosIceMessage::MotorData_<ContainerAllocator> >::stream(s, indent + "  ", v.motorMsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_MOTORSSRVRESPONSE_H
