// Generated by gencpp from file RosIceMessage/Pose3DMotorsData.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_POSE3DMOTORSDATA_H
#define ROSICEMESSAGE_MESSAGE_POSE3DMOTORSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RosIceMessage
{
template <class ContainerAllocator>
struct Pose3DMotorsData_
{
  typedef Pose3DMotorsData_<ContainerAllocator> Type;

  Pose3DMotorsData_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , pan(0.0)
    , tilt(0.0)
    , roll(0.0)
    , panSpeed(0.0)
    , tiltSpeed(0.0)
    , maxPan(0.0)
    , minPan(0.0)
    , maxTilt(0.0)
    , minTilt(0.0)
    , maxPanSpeed(0.0)
    , maxTiltSpeed(0.0)  {
    }
  Pose3DMotorsData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , pan(0.0)
    , tilt(0.0)
    , roll(0.0)
    , panSpeed(0.0)
    , tiltSpeed(0.0)
    , maxPan(0.0)
    , minPan(0.0)
    , maxTilt(0.0)
    , minTilt(0.0)
    , maxPanSpeed(0.0)
    , maxTiltSpeed(0.0)  {
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _panSpeed_type;
  _panSpeed_type panSpeed;

   typedef float _tiltSpeed_type;
  _tiltSpeed_type tiltSpeed;

   typedef float _maxPan_type;
  _maxPan_type maxPan;

   typedef float _minPan_type;
  _minPan_type minPan;

   typedef float _maxTilt_type;
  _maxTilt_type maxTilt;

   typedef float _minTilt_type;
  _minTilt_type minTilt;

   typedef float _maxPanSpeed_type;
  _maxPanSpeed_type maxPanSpeed;

   typedef float _maxTiltSpeed_type;
  _maxTiltSpeed_type maxTiltSpeed;




  typedef boost::shared_ptr< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> const> ConstPtr;

}; // struct Pose3DMotorsData_

typedef ::RosIceMessage::Pose3DMotorsData_<std::allocator<void> > Pose3DMotorsData;

typedef boost::shared_ptr< ::RosIceMessage::Pose3DMotorsData > Pose3DMotorsDataPtr;
typedef boost::shared_ptr< ::RosIceMessage::Pose3DMotorsData const> Pose3DMotorsDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RosIceMessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'RosIceMessage': ['/home/ace15/Documents/JdeRobot/GoogleSummer/JdeRobot2015/catkin_ws/src/RosIceMessage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c440b44f562a464d9110a18820d3c5d1";
  }

  static const char* value(const ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc440b44f562a464dULL;
  static const uint64_t static_value2 = 0x9110a18820d3c5d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/Pose3DMotorsData";
  }

  static const char* value(const ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 pan\n\
float32 tilt\n\
float32 roll\n\
float32 panSpeed\n\
float32 tiltSpeed\n\
float32 maxPan\n\
float32 minPan\n\
float32 maxTilt\n\
float32 minTilt\n\
float32 maxPanSpeed\n\
float32 maxTiltSpeed\n\
";
  }

  static const char* value(const ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.pan);
      stream.next(m.tilt);
      stream.next(m.roll);
      stream.next(m.panSpeed);
      stream.next(m.tiltSpeed);
      stream.next(m.maxPan);
      stream.next(m.minPan);
      stream.next(m.maxTilt);
      stream.next(m.minTilt);
      stream.next(m.maxPanSpeed);
      stream.next(m.maxTiltSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pose3DMotorsData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosIceMessage::Pose3DMotorsData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "panSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.panSpeed);
    s << indent << "tiltSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.tiltSpeed);
    s << indent << "maxPan: ";
    Printer<float>::stream(s, indent + "  ", v.maxPan);
    s << indent << "minPan: ";
    Printer<float>::stream(s, indent + "  ", v.minPan);
    s << indent << "maxTilt: ";
    Printer<float>::stream(s, indent + "  ", v.maxTilt);
    s << indent << "minTilt: ";
    Printer<float>::stream(s, indent + "  ", v.minTilt);
    s << indent << "maxPanSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.maxPanSpeed);
    s << indent << "maxTiltSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.maxTiltSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_POSE3DMOTORSDATA_H
