// Generated by gencpp from file RosIceMessage/CMDVelData.msg
// DO NOT EDIT!


#ifndef ROSICEMESSAGE_MESSAGE_CMDVELDATA_H
#define ROSICEMESSAGE_MESSAGE_CMDVELDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RosIceMessage
{
template <class ContainerAllocator>
struct CMDVelData_
{
  typedef CMDVelData_<ContainerAllocator> Type;

  CMDVelData_()
    : linearX(0.0)
    , linearY(0.0)
    , linearZ(0.0)
    , angularX(0.0)
    , angularY(0.0)
    , angularZ(0.0)  {
    }
  CMDVelData_(const ContainerAllocator& _alloc)
    : linearX(0.0)
    , linearY(0.0)
    , linearZ(0.0)
    , angularX(0.0)
    , angularY(0.0)
    , angularZ(0.0)  {
    }



   typedef double _linearX_type;
  _linearX_type linearX;

   typedef double _linearY_type;
  _linearY_type linearY;

   typedef double _linearZ_type;
  _linearZ_type linearZ;

   typedef double _angularX_type;
  _angularX_type angularX;

   typedef double _angularY_type;
  _angularY_type angularY;

   typedef double _angularZ_type;
  _angularZ_type angularZ;




  typedef boost::shared_ptr< ::RosIceMessage::CMDVelData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RosIceMessage::CMDVelData_<ContainerAllocator> const> ConstPtr;

}; // struct CMDVelData_

typedef ::RosIceMessage::CMDVelData_<std::allocator<void> > CMDVelData;

typedef boost::shared_ptr< ::RosIceMessage::CMDVelData > CMDVelDataPtr;
typedef boost::shared_ptr< ::RosIceMessage::CMDVelData const> CMDVelDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RosIceMessage::CMDVelData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RosIceMessage::CMDVelData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RosIceMessage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'RosIceMessage': ['/home/ace15/Documents/JdeRobot/GoogleSummer/JdeRobot2015/catkin_ws/src/RosIceMessage/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RosIceMessage::CMDVelData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RosIceMessage::CMDVelData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RosIceMessage::CMDVelData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c31f4d194cd1718743d5f47f9ef8256";
  }

  static const char* value(const ::RosIceMessage::CMDVelData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c31f4d194cd1718ULL;
  static const uint64_t static_value2 = 0x743d5f47f9ef8256ULL;
};

template<class ContainerAllocator>
struct DataType< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RosIceMessage/CMDVelData";
  }

  static const char* value(const ::RosIceMessage::CMDVelData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linearX\n\
float64 linearY\n\
float64 linearZ\n\
float64 angularX\n\
float64 angularY\n\
float64 angularZ\n\
";
  }

  static const char* value(const ::RosIceMessage::CMDVelData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linearX);
      stream.next(m.linearY);
      stream.next(m.linearZ);
      stream.next(m.angularX);
      stream.next(m.angularY);
      stream.next(m.angularZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CMDVelData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RosIceMessage::CMDVelData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RosIceMessage::CMDVelData_<ContainerAllocator>& v)
  {
    s << indent << "linearX: ";
    Printer<double>::stream(s, indent + "  ", v.linearX);
    s << indent << "linearY: ";
    Printer<double>::stream(s, indent + "  ", v.linearY);
    s << indent << "linearZ: ";
    Printer<double>::stream(s, indent + "  ", v.linearZ);
    s << indent << "angularX: ";
    Printer<double>::stream(s, indent + "  ", v.angularX);
    s << indent << "angularY: ";
    Printer<double>::stream(s, indent + "  ", v.angularY);
    s << indent << "angularZ: ";
    Printer<double>::stream(s, indent + "  ", v.angularZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSICEMESSAGE_MESSAGE_CMDVELDATA_H
